version: '3.1'
services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./files/nginx-load-balancer.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: httpd-python38-psycopg2_b
    ports:
      - 8081:8080

  web2:
    image: httpd-python38-psycopg2_b
    ports:
      - 8082:8080

  web3:
    image: httpd-python38-psycopg2_b
    ports:
      - 8083:8080
